//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deepwell.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryLog
    {
        public long InventoryLogId { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public int ProductId { get; set; }
        public int LocationId { get; set; }
        public string Source { get; set; }
        public string Action { get; set; }
        public string ChangeType { get; set; }
        public Nullable<int> FromLocationId { get; set; }
        public Nullable<int> ToLocationId { get; set; }
        public int QuantityAffected { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
