//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deepwell.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetail()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.OrderProcessDetails = new HashSet<OrderProcessDetail>();
        }
    
        public int OrderDetailId { get; set; }
        public int OrderId { get; set; }
        public short LineNumber { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public bool ProductTaxable { get; set; }
        public int LocationId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public short StatusId { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string ProductNumber { get; set; }
        public decimal ListPrice { get; set; }
        public Nullable<int> InvoicedQuantity { get; set; }
        public Nullable<int> ShippedQuantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual OrderHeader OrderHeader { get; set; }
        public virtual OrderItemStatu OrderItemStatu { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProcessDetail> OrderProcessDetails { get; set; }
    }
}
