//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deepwell.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderProcess()
        {
            this.OrderProcessDetails = new HashSet<OrderProcessDetail>();
        }
    
        public int OrderProcessId { get; set; }
        public int OrderId { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<decimal> Total { get; set; }
        public bool IsInvoiced { get; set; }
        public Nullable<System.DateTime> DateInvoiced { get; set; }
        public bool IsShipped { get; set; }
        public Nullable<System.DateTime> DateShipped { get; set; }
        public string PoNumber { get; set; }
        public string ShippingVia { get; set; }
        public string TrackingId { get; set; }
        public int Owner { get; set; }
        public string Comments { get; set; }
        public bool IsReturned { get; set; }
        public Nullable<System.DateTime> DateReturned { get; set; }
    
        public virtual OrderHeader OrderHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProcessDetail> OrderProcessDetails { get; set; }
    }
}
