//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deepwell.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProcessDetail
    {
        public int OrderProcessDetailId { get; set; }
        public int OrderProcessId { get; set; }
        public int OrderDetailId { get; set; }
        public Nullable<int> OriginalOrderDetailId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual OrderProcess OrderProcess { get; set; }
    }
}
