//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deepwell.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductComponent
    {
        public int ComponentId { get; set; }
        public int MudProductId { get; set; }
        public int ComponentProductId { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
